baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Homepage" #accessible via {{ .Site.Title }}

# Can add global site params below
[params]
  author = "Eva T" # accessible via {{ .Site.Params.author }}
  description = "My website"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
